### ISSUE TITLE
hoxy.. 제가 만든 map_valid_tester 도 추가해주실 수 있나요?

### ISSUE THREAD

**Issue by humblEgo** [taelee42/mlx_example#2]
taelee님 안녕하세요~ merge해주셔서 감사합니다. 저도 완전 잊고 있었네요ㅎㅎ;

다름이 아니라 제가 cub3D map의 유효성을 검사하는데 도움받을 수 있도록 test_map을 모아서 한방에 실험해볼 수 있는
[map_valid_tester](https://github.com/humblEgo/cub3D_map_tester) 를 만들었었는데요, 혹시 괜찮으시다면 이것도 문서에 추가해주실 수 있으신지요~?

앞으로 42seoul learner분들이 taelee님 깃헙 많이 참고하시고 도움받으실 수 있을 것 같아서 여쭙니당~

물론 애매하면 편하게 거절해주세요~ :)

**Comment by terry-yes** [comment]
반영 했습니다!!
이번에도 늦었네요ㅎㅎ
좋은 말씀 감사합니다~!!
