### ISSUE TITLE
mlx_example/02key_handling/main.c: 63: A Key

### ISSUE THREAD

**Issue by hyulim42** [taelee42/mlx_example#4]
https://github.com/taelee42/mlx_example/blob/master/02key_handling/main.c
```
	printf("'A key': Subtract 1 from x\n");
```
정황상 A key 가 아닌 S Key 인것 같습니다.

**Comment by terry-yes** [comment]
감사합니다!! 
ykoh님의 풀리퀘로 수정되었습니다~
